#!/bin/bash
# This program implements the protocol in "Polarizable Atomic Multipole-Based 
# Molecular Mechanics for Organic Molecules" by P. Ren
# It assumes that the correct environmental variables have been set up properly.
# See setup.sh in the same directory
# Author: Kailong Mao

# Usage: get_rmsd.sh

# Step 1: Run g09, get the checkpoint file, and convert it to correct format
modified_p="/user/jrackers/tinker-git/bin/potential-git"
near_grid_key="/user/mao/Desktop/scripts/near_grid.key"
fitting_key="/user/mao/Desktop/scripts/fitting.key"
charge_penetration_key="/user/mao/Desktop/scripts/charge_penetration.key"

for i in *.xyz
do
	base_name="${i%.*}"
	echo "Working on ${base_name} ..."

	# Skip molecules with missing files
	if ! [ -e ${base_name}_isa.key ] || ! [ -e ${base_name}_far.pot ]
	then
		echo "Skipped ${base_name}"
		continue
	fi

	# Step 3: Calculate the potential RMSD and fitted potential RMSD
	for j in ${base_name}_*.key
	do
		echo "Testing $j"
		echo "    Calculating RMSD based on far grid"
		printf "===============================\n" >> ${base_name}.rmsd
		printf ${j}"\n" >> ${base_name}.rmsd
		printf "\tFar grid:\n" >> ${base_name}.rmsd
		potential 5 $i $j ${base_name}_far.pot N | tail -1 | awk '{print "\tOriginal: "$NF}' >> ${base_name}.rmsd
		potential -k $fitting_key 6 $i $j ${base_name}_far.pot N 0.1 | tail -1 | awk '{print "\tFitted: "$NF}' >> ${base_name}.rmsd

		# Ensure the fitted parameters give a symmetrical molecule
		expect -c '
			spawn poledit 3 '" $i ${base_name}.key"'
			expect {
				Average { send "Y\r"; exp_continue }
				Remove { send  "Y\r"; exp_continue }
			}
		' >/dev/null

		mv ${base_name}.key ${j%.*}.key_fitted_asymm
		mv ${base_name}.key_2 ${j%.*}.key_fitted

		# Add the missing atom info to fitted key
		# cat ${j%.*}.key_fitted > temp.key_fitted
		# cat ${j%.*}.key | grep "atom" > ${j%.*}.key_fitted
		# cat temp.key_fitted >> ${j%.*}.key_fitted
		# rm temp.key_fitted

		# Append atom information to fitted multipoles parameter files generated by POTENTIAL 5 for use by Josh's POTENTIAL program
		echo -e "$(cat ${j%.*}.key | grep "atom")\n\n$(cat ${j%.*}.key_fitted)" > ${j%.*}.key_fitted
		printf "\n" >> ${base_name}.rmsd

		echo "    Calculating RMSD based on near grid"
		printf "\tNear grid:\n" >> ${base_name}.rmsd
		potential 5 $i $j ${base_name}_near.pot N | tail -1 | awk '{print "\tOriginal: "$NF}' >> ${base_name}.rmsd
		potential 5 $i ${j%.*}.key_fitted ${base_name}_near.pot N | tail -1 | awk '{print "\tFitted: "$NF}' >> ${base_name}.rmsd
		printf "\n" >> ${base_name}.rmsd

		echo "    Calculating RMSD based on near grid with charge penetration"
		printf "\tNear grid with charge_penetration:\n" >> ${base_name}.rmsd
		$modified_p -k ${base_name}.cp 5 $i $j ${base_name}_near.pot N | tail -1 | awk '{print "\tOriginal: "$NF}' >> ${base_name}.rmsd
		$modified_p -k ${base_name}.cp 5 $i ${j%.*}.key_fitted ${base_name}_near.pot N | tail -1 | awk '{print "\tFitted: "$NF}' >> ${base_name}.rmsd
		printf "\n" >> ${base_name}.rmsd
		break
	done
	echo "Finished ${base_name}"
done